#! /bin/bash

while true; do
	rep=0;
	read -n 1 -s B
	if [ $B == "3" ]
	then
		rep=$(( $rep+1 ))
		read -t 1 -n 1 -s B
		if [[ $? -eq 0 ]] && [[ $B == "3" ]]
		then
			rep=$(( $rep+1 ))
			read -t 1 -n 1 -s B
			if [[ $? -eq 0 ]] && [[ $B == "3" ]]
			then
				rep=$(( $rep+1 ))
			fi
		fi
	fi
	echo "this $rep"
done

